FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 1937
EXPOSE 44354

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["IPC.Web/IPC.Web.csproj", "IPC.Web/"]
COPY ["IPC.Common/IPC.Common.csproj", "IPC.Common/"]
COPY ["IPC.CacheClient/IPC.CacheClient.csproj", "IPC.CacheClient/"]
COPY ["IPC.Core/IPC.Core.csproj", "IPC.Core/"]
RUN dotnet restore "IPC.Web/IPC.Web.csproj"
COPY . .
WORKDIR "/src/IPC.Web"
RUN dotnet build "IPC.Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IPC.Web.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IPC.Web.dll"]