FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app
EXPOSE 10021

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["IPC.Core/IPC.Core.csproj", "IPC.Core/"]
COPY ["IPC.Common/IPC.Common.csproj", "IPC.Common/"]
COPY ["Server.Cache/IPC.CacheServer.csproj", "Server.Cache/"]
RUN dotnet restore "Server.Cache/IPC.CacheServer.csproj"
COPY . .
WORKDIR "/src/Server.Cache"
RUN dotnet build "IPC.CacheServer.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IPC.CacheServer.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IPC.CacheServer.dll"]

