FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5001
EXPOSE 44378

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["IPC.WebFile/IPC.WebFile.csproj", "IPC.WebFile/"]
COPY ["IPC.Common/IPC.Common.csproj", "IPC.Common/"]
COPY ["IPC.CacheClient/IPC.CacheClient.csproj", "IPC.CacheClient/"]
COPY ["IPC.Core/IPC.Core.csproj", "IPC.Core/"]
RUN dotnet restore "IPC.WebFile/IPC.WebFile.csproj"
COPY . .
WORKDIR "/src/IPC.WebFile"
RUN dotnet build "IPC.WebFile.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IPC.WebFile.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IPC.WebFile.dll"]