FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 65016
EXPOSE 44376

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["IpcPocV2.Common/IpcPocV2.Common.csproj", "IpcPocV2.Common/"]
COPY ["IpcPocV2.Client.File/IpcPocV2.Client.File.csproj", "IpcPocV2.Client.File/"]
RUN dotnet restore "IpcPocV2.Client.File/IpcPocV2.Client.File.csproj"
COPY . .
WORKDIR "/src/IpcPocV2.Client.File"
RUN dotnet build "IpcPocV2.Client.File.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IpcPocV2.Client.File.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IpcPocV2.Client.File.dll", "--urls", "http://*:5001"]