FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app
EXPOSE 10041

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["IpcPocV2.Server.QueueConsumer/IpcPocV2.Server.QueueConsumer.csproj", "IpcPocV2.Server.QueueConsumer/"]
RUN dotnet restore "IpcPocV2.Server.QueueConsumer/IpcPocV2.Server.QueueConsumer.csproj"
COPY . .
WORKDIR "/src/IpcPocV2.Server.QueueConsumer"
RUN dotnet build "IpcPocV2.Server.QueueConsumer.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IpcPocV2.Server.QueueConsumer.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "IpcPocV2.Server.QueueConsumer.dll"]

